// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Endereco = new HashSet<Endereco>();
            Entrada = new HashSet<Entrada>();
        }

        public int Clcodigo { get; set; }
        public string Clnome { get; set; }
        public int? ClcodTipoCliente { get; set; }
        public string Clcpf { get; set; }
        public string Clemail { get; set; }
        public string Clcnpj { get; set; }
        public string Cltelefone { get; set; }
        public string Clrg { get; set; }
        public DateTime? CldataNascimento { get; set; }
        public DateTime? CldataCadastro { get; set; }
        public string Clsexo { get; set; }

        public virtual TipoCliente ClcodTipoClienteNavigation { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<Entrada> Entrada { get; set; }
    }
}