// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Endereco
    {
        public int Encodigo { get; set; }
        public int? EncodCliente { get; set; }
        public int? EncodUnidade { get; set; }
        public int? EncodTipoLogradouro { get; set; }
        public string Enlogradouro { get; set; }
        public string Ennumero { get; set; }
        public string Encomplemento { get; set; }
        public string Enbairro { get; set; }
        public string Encidade { get; set; }
        public string Enestado { get; set; }
        public decimal? Enlatitude { get; set; }
        public decimal? EnLongitude { get; set; }
        public string Encep { get; set; }
        public int? EncodRegiao { get; set; }

        public virtual Cliente EncodClienteNavigation { get; set; }
        public virtual Regiao EncodRegiaoNavigation { get; set; }
        public virtual TipoLogradouro EncodTipoLogradouroNavigation { get; set; }
        public virtual Unidades EncodUnidadeNavigation { get; set; }
    }
}