// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Entregadores
    {
        public Entregadores()
        {
            MovimentacaoMocoEntregadorNavigation = new HashSet<Movimentacao>();
            MovimentacaoMocodEntregadorNavigation = new HashSet<Movimentacao>();
            Pickup = new HashSet<Pickup>();
        }

        public int Etcodigo { get; set; }
        public string Etnome { get; set; }
        public string Ettelefone { get; set; }
        public int? EtcodUnidade { get; set; }

        public virtual Unidades EtcodUnidadeNavigation { get; set; }
        public virtual ICollection<Movimentacao> MovimentacaoMocoEntregadorNavigation { get; set; }
        public virtual ICollection<Movimentacao> MovimentacaoMocodEntregadorNavigation { get; set; }
        public virtual ICollection<Pickup> Pickup { get; set; }
    }
}