// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class EntradaItens
    {
        public int Eicodigo { get; set; }
        public int? EicodEntrada { get; set; }
        public decimal? Eipeso { get; set; }
        public string Eidescricao { get; set; }
        public decimal? Eilargura { get; set; }
        public decimal? Eialtura { get; set; }
        public decimal? Eicomprimento { get; set; }
        public decimal? Eivalor { get; set; }

        public virtual Entrada EicodEntradaNavigation { get; set; }
    }
}