// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Ocorrencia
    {
        public int Occodigo { get; set; }
        public string Ocdescricao { get; set; }
        public int? OccodTipoOcorrencia { get; set; }
        public DateTime? Ocdata { get; set; }
        public int? OccodResultadoOcorrencia { get; set; }
        public int? OccodEntrada { get; set; }

        public virtual Entrada OccodEntradaNavigation { get; set; }
        public virtual ResultadoOcorrencia OccodResultadoOcorrenciaNavigation { get; set; }
        public virtual TipoOcorrencia OccodTipoOcorrenciaNavigation { get; set; }
    }
}