// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Regiao
    {
        public Regiao()
        {
            Endereco = new HashSet<Endereco>();
        }

        public int Recodigo { get; set; }
        public string Redescricao { get; set; }

        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}