// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class ResultadoOcorrencia
    {
        public ResultadoOcorrencia()
        {
            Ocorrencia = new HashSet<Ocorrencia>();
        }

        public int Rccodigo { get; set; }
        public string Rcdescricao { get; set; }

        public virtual ICollection<Ocorrencia> Ocorrencia { get; set; }
    }
}