// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Rota
    {
        public int Rocodigo { get; set; }
        public int? RocodEntrada { get; set; }
        public int? RocodUnidade { get; set; }
        public int? RocodUnidadeOrigem { get; set; }
        public bool RoultimaEtapa { get; set; }

        public virtual Entrada RocodEntradaNavigation { get; set; }
        public virtual Unidades RocodUnidadeNavigation { get; set; }
        public virtual Unidades RocodUnidadeOrigemNavigation { get; set; }
    }
}