// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Status
    {
        public Status()
        {
            Devolucao = new HashSet<Devolucao>();
            Transporte = new HashSet<Transporte>();
        }

        public int Stcodigo { get; set; }
        public string Stdescricao { get; set; }

        public virtual ICollection<Devolucao> Devolucao { get; set; }
        public virtual ICollection<Transporte> Transporte { get; set; }
    }
}