// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class TipoOcorrencia
    {
        public TipoOcorrencia()
        {
            Ocorrencia = new HashSet<Ocorrencia>();
        }

        public int Tccodigo { get; set; }
        public string Tcdescricao { get; set; }

        public virtual ICollection<Ocorrencia> Ocorrencia { get; set; }
    }
}