// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class TipoLogradouro
    {
        public TipoLogradouro()
        {
            Endereco = new HashSet<Endereco>();
        }

        public int Tlcodigo { get; set; }
        public string Tldescricao { get; set; }

        public virtual ICollection<Endereco> Endereco { get; set; }
    }
}