// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Unidades
    {
        public Unidades()
        {
            DevolucaoDecodUnidadeDestinoNavigation = new HashSet<Devolucao>();
            DevolucaoDecodUnidadeOrigemNavigation = new HashSet<Devolucao>();
            DistanciaUnidadeDucodUnidadeDestinoNavigation = new HashSet<DistanciaUnidade>();
            DistanciaUnidadeDucodUnidadeOrigemNavigation = new HashSet<DistanciaUnidade>();
            Endereco = new HashSet<Endereco>();
            EntradaErcodUnidadeDestinoNavigation = new HashSet<Entrada>();
            EntradaErcodUnidadeNavigation = new HashSet<Entrada>();
            Entregadores = new HashSet<Entregadores>();
            Movimentacao = new HashSet<Movimentacao>();
            Pickup = new HashSet<Pickup>();
            RotaRocodUnidadeNavigation = new HashSet<Rota>();
            RotaRocodUnidadeOrigemNavigation = new HashSet<Rota>();
            Usuario = new HashSet<Usuario>();
            Veiculo = new HashSet<Veiculo>();
        }

        public int Uncodigo { get; set; }
        public string Undescricao { get; set; }
        public string Uncidade { get; set; }
        public string Unestado { get; set; }
        public bool Unhub { get; set; }

        public virtual ICollection<Devolucao> DevolucaoDecodUnidadeDestinoNavigation { get; set; }
        public virtual ICollection<Devolucao> DevolucaoDecodUnidadeOrigemNavigation { get; set; }
        public virtual ICollection<DistanciaUnidade> DistanciaUnidadeDucodUnidadeDestinoNavigation { get; set; }
        public virtual ICollection<DistanciaUnidade> DistanciaUnidadeDucodUnidadeOrigemNavigation { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<Entrada> EntradaErcodUnidadeDestinoNavigation { get; set; }
        public virtual ICollection<Entrada> EntradaErcodUnidadeNavigation { get; set; }
        public virtual ICollection<Entregadores> Entregadores { get; set; }
        public virtual ICollection<Movimentacao> Movimentacao { get; set; }
        public virtual ICollection<Pickup> Pickup { get; set; }
        public virtual ICollection<Rota> RotaRocodUnidadeNavigation { get; set; }
        public virtual ICollection<Rota> RotaRocodUnidadeOrigemNavigation { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}