// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Usuario
    {
        public Usuario()
        {
            GrupoUsuario = new HashSet<GrupoUsuario>();
        }

        public int Uscodigo { get; set; }
        public string Usnome { get; set; }
        public string Ussenha { get; set; }
        public bool? Usdesativado { get; set; }
        public int? UscodUnidade { get; set; }

        public virtual Unidades UscodUnidadeNavigation { get; set; }
        public virtual ICollection<GrupoUsuario> GrupoUsuario { get; set; }
    }
}