// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class Veiculo
    {
        public int Vecodigo { get; set; }
        public string Vedescricao { get; set; }
        public string Vetipo { get; set; }
        public string Veplaca { get; set; }
        public int? Veano { get; set; }
        public string VecorPredominante { get; set; }
        public int? VecodUnidade { get; set; }

        public virtual Unidades VecodUnidadeNavigation { get; set; }
    }
}