// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class VwDevolucaoMes
    {
        public int Ano { get; set; }
        public int Mes { get; set; }
        public int Total { get; set; }
    }
}