// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Transportadora.Model.Models
{
    public partial class VwUtilizacaoAnual
    {
        public int Ano { get; set; }
        public string ClNome { get; set; }
        public int Janeiro { get; set; }
        public int Fevereiro { get; set; }
        public int Marco { get; set; }
        public int Abril { get; set; }
        public int Maio { get; set; }
        public int Junho { get; set; }
        public int Julho { get; set; }
        public int Agosto { get; set; }
        public int Setembro { get; set; }
        public int Outubro { get; set; }
        public int Novembro { get; set; }
        public int Dezembro { get; set; }
        public int TotalAnual { get; set; }
    }
}